# Base configs
baseurl: "https://photography.rampatra.com"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Brian Tries to Cook"
subtitle: "A small taste of what I cook"
author: "Brian Kim"
header:
 title: "Brian Tries to Cook"
 subtitle: "by Brian Kim"
footer:
 name: "Hey there, my name is Brian!"
 bio: "This is a small space where I want to showcase the meals that I have made."
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: "https://www.twitter.com/bkim211"
  instagram: "https://www.instagram.com/brianrkim"
  linkedin: "https://in.linkedin.com/in/brian-kim-86b6a0140/"
